### ISSUE TITLE
nodered fails to build

### ISSUE THREAD

**Issue by commentsonly** [echtelerp/IoT-Stack-tutorial#1]
thought it's a nice and well documented guidance but after

docker-compose up -d

all I get is

Error: Service 'nodered' failed to build : Build failed

dammit .... error solved ..... one must must take care to not accidently add a wrong number to the static dns server, since it doensn't matter until that docker-compose up stage which then errors.

means ..... issue could get closed asap :-)

**Comment by echtelerp** [comment]
Happy that it is resolved 
Thanks for following the tutorial 

I'll close the issue :-)
